// A local fall-back corpus keeps the opening legible when the site is opened
// directly from disk. The loaded Hyperbook enlarges this to the full 40-quote
// selection and adds exact page-highlight rectangles.
export const openingQuotes = Object.freeze([
  { id: "quote:001-a-hypercity-is-a-real-city-overlaid-with-thick-infor", page: 6, text: "A HyperCity is a real city overlaid with thick information networks that not only catalyze the present but also go back in time to document the past and go forward to project future possibilities." },
  { id: "quote:009-the-book-also-features-contributions-written-and-des", page: 10, text: "The book also features contributions written and designed by project leaders that open up as“windows” onto the HyperCities idea and digital cultural mapping more generally." },
  { id: "quote:012-imagine-a-search-and-discovery-tool-for-this-web-in", page: 13, text: "Imagine a search and discovery tool for this web in which you traveled through time and space, rather than inputting keywords in an empty white box." },
  { id: "quote:154-mapping-is-not-a-one-time-thing-and-maps-are-not-st", page: 15, text: "Mapping is not a one-time thing, and maps are not stable objects that reference, reflect, or correspond to an external reality." },
  { id: "quote:019-in-other-words-maybe-the-past-is-always-there-quiet", page: 23, text: "In other words, maybe the past is always there—quiet, muted, faded, hidden—and it is the task of the flâneur to enable it to speak, to make it come alive and come to light, and, thereby, resonate with the present." },
  { id: "quote:030-through-the-google-maps-and-earth-apis-hypercities", page: 35, text: "Through the Google Maps and Earth APIs, HyperCities essentially allows users to go back in time to create, narrate, and explore the historical layers of city spaces and tell stories in an interactive, hypermedia environment." },
  { id: "quote:048-thick-mapping-begins-to-look-like-an-ever-expanding", page: 65, text: "Thick mapping begins to look like an ever-expanding railway system that moves out and downward at the same time, giving rise to a participatory web of intersecting cities, voices, streets, memories, and narratives." },
  { id: "quote:090-as-much-as-thick-mapping-is-interested-in-denatural", page: 118, text: "As much as“thick mapping” is interested in denaturalizing any geographic information system as a construction of projections, coordinate systems, and representational practices, georeferencing can also reveal ideologies at the level of spatial systems." },
  { id: "quote:096-from-its-inception-the-dynamic-hypercities-platform", page: 128, text: "From its inception the dynamic HyperCities platform has enabled the exploration of content as well as content delivery systems, encouraging scholars to take vertical, animated, collaborative, iterative leaps across and through fields, approaches, data, space and time." },
  { id: "quote:112-these-archives-are-not-simply-documents-of-the-past", page: 149, text: "These archives are not simply documents of the past (“what was”) but are spectral, in that they pose haunting questions about the possibility of a future and, therefore, are motivated by a responsibility or promise that remains open and undetermined." },
  { id: "quote:119-events-are-ever-thicker-networks-of-events-no-matte", page: 156, text: "Events are ever thicker networks of events, no matter how zoomed in or zoomed out one is." },
  { id: "quote:126-in-every-case-the-archive-is-less-than-the-event-a", page: 168, text: "In every case, the archive is“less” than the event and functions primarily as a possible but always incomplete documentation of the past through the contingency of the present." },
  { id: "quote:132-at-the-same-time-the-team-used-the-perspectives-and", page: 176, text: "At the same time, the team used the perspectives and patterns of the data in aggregate to “zoom in” to particular individuals and follow individual stories unfolding." },
  { id: "quote:137-living-abroad-gave-me-the-opportunity-to-analyze-the", page: 184, text: "Living abroad gave me the opportunity to analyze the “big” picture, taking a macro-level approach and applying computational analysis on a large, even abstracted and high-altitude scale." },
  { id: "quote:153-the-event-has-many-lives-and-afterlives-through-haun", page: 202, text: "The event has many lives and afterlives through haunting absences, stranded memories, and empty landscapes." },
  { id: "quote:160-the-event-remains", page: 203, text: "The event remains." }
]);
